# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: $(Build.DefinitionName).$(SourceBranchName).$(BuildID)

trigger:
- master
  
stages:
- stage: Prebuild
  jobs:
  - job: Tests
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - task: DotNetCoreCLI@2
      displayName: dotnet restore
      inputs:
        command: 'restore'
        projects: 'tests/Gestures.Tests/Gestures.Tests.csproj'
    - task: DotNetCoreCLI@2
      displayName: dotnet test
      inputs:
        command: 'test'
        projects: 'tests/Gestures.Tests/Gestures.Tests.csproj'
